export const HIDE_FLASH = 'HIDE_FLASH'
export const SHOW_FLASH = 'SHOW_FLASH'

export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const LOG_OUT = 'LOG_OUT'

export const ADD_CLASSES = 'ADD_CLASSES'
export const SET_CLASSES = 'SET_CLASSES'
export const DELETE_CLASS = 'DELETE_CLASS'

export const SET_CLASS_STUDENTS = 'SET_CLASS_STUDENTS'
export const DELETE_CLASS_STUDENT = 'DELETE_CLASS_STUDENT'
export const ADD_CLASS_STUDENTS = 'ADD_CLASS_STUDENTS'

export const ADD_STUDENTS = 'ADD_STUDENTS'
export const DELETE_STUDENT = 'DELETE_STUDENT'

export const ADD_USERS = 'ADD_USERS'
export const SET_USERS = 'SET_USERS'
export const DELETE_USER = 'DELETE_USER'